modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="automobility"
version="${version}"
displayName="Automobility: Refueled"
logoFile="automobility.png"
authors="FoundationGames, Nobacon4u" #optional
description='''
Vehicles and whatnot, now with resourcepack support!
'''

[[dependencies.automobility]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.automobility]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
